version: '3'

services:
  fivem:
    build: .
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    volumes:
      - ./resources:/opt/cfx-server-data/resources
      - ./server.cfg:/opt/cfx-server-data/server.cfg
    environment:
      LICENSE_KEY: "${LICENSE_KEY}"
    tty: true
    stdin_open: true
